version: '3.7'
services:
    dbserver:
        image: mysql:5.7.32
        container_name: dbserver
        environment: 
            MYSQL_ROOT_PASSWORD: mysqlpw
        volumes:
            - ./bd/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 3306:3306
        networks:
            - net
    jenkins:
        image: jenkins/jenkins
        ports:
            - 8080:8080
            - 50000:50000
        container_name: jenkins
        networks:
            - net
    python:
        container_name: app
        build: ./app
        environment:
            DISPLAY: :0
        volumes: 
            - /tmp/.X11-unix:/tmp/.X11-unix
        networks:
            - net
networks:
    net: