version: '3.7'
services:
    dbserver:
        build: ./bd
        container_name: dbserver
        environment: 
            MYSQL_ROOT_PASSWORD: mysqlpw
        ports:
            - 3306:3306
        networks:
            - net
    jenkins:
        image: jenkins/jenkins
        ports:
            - 8080:8080
            - 50000:50000
        container_name: jenkins
        networks:
            - net
    app_v1:
        container_name: app
        build: ./app
        environment:
            DISPLAY: :0
        volumes: 
            - /tmp/.X11-unix:/tmp/.X11-unix
        networks:
            - net
        depends_on:
            - dbserver
networks:
    net: